[Variables]
; Language and Location
Language=English
Location=MXDF0132
Unit=m
Format=%#I:%M

; Mouse increment
ScrollMouseIncrement=0.05
ScrollMouseIncrement2=50

; Visibility
Hidden=1
Hidden2=0
IconSetting=1

; Player music
Player=Spotify

; Colors
Color1=255,255,255
Color2=13,13,13
Color3=106,121,235

; Date event
Day=25
Month=5
Year=2026
textEvent=<3

; Slides show
IMGFolder4=none
IMGFolder3=none
IMGFolder1=none
time=60

; Img Notes
IMGNotes=#@#img\4.png
