[Variables]
; Language and Location
Language=English
Location=MXDF0132
Unit=m
Format=%H:%M

; Mouse increment
ScrollMouseIncrement=0.05
ScrollMouseIncrement2=50

; Visibility
Hidden=0
Hidden2=1
IconSetting=1

; Player music
Player=Winamp

; Colors
Color1=255,255,255
Color2=13,13,13
Color3=250,155,176

; Date event
Day=25
Month=5
Year=2026
textEvent=aniversario

; Img Notes
IMGNotes=5.png

; Slides show
IMGFolder=IMGFolder='C:\Users\Areli Guevara\OneDrive\Im???genes\Wallpapers'
PreserveRatio=2
Scale=1.2
