[Variables]
; Language and Location
Language=English
Location=MXDF0132
Unit=m
Format=%#I:%M

; Mouse increment
ScrollMouseIncrement=0.05
ScrollMouseIncrement2=50

; Visibility
Hidden=1
Hidden2=0

; Player music
Player=Winamp

; Colors
Color1=255,255,255
Color2=13,13,13
Color3=217,47,143

; Date event
Day=3
Month=5
Year=2026
textEvent=aniversario

; Img Notes
IMGNotes=6.png

; Slides show
IMGFolder=IMGFolder='C:\Users\Areli Guevara\OneDrive\Im???genes\Wallpapers'
PreserveRatio=2
